[package]
name = "duplicate-file-deletor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
csv = "1.2"
eframe = "0.31"
egui = "0.31"
env_logger = "0.10"
log = "0.4"
rayon = "1.7"
rfd = "0.15"
serde = { version = "1.0", features = ["derive"] }
walkdir = "2.3"
trash = "3"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
